### ISSUE TITLE
(feature request) enable to accept object name to identify it in action parameters

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-vsphere#3]
Thank you for providing much useful pack.

I have a feature request of this pack.

Most of actions in this pack, e.g. `get_vms`, `vm_create_from_template`, and so on, require MOID (Managed Object Reference ID) in parameters to identify object.
But most users are unfamiliar with it because MOID (like `datastore-412`) is not user friendly and it's hard to refer from vSphere (Web) Client.

In contrast, object-name (like `ceph-dc1-f2`) is easily understandable for user and easily referenced.
So I think it become more usable to extend it to accept object name in action parameters.

Thank you.

**Comment by userlocalhost** [comment]
I think this requirement is satisfied with the action that transforms MOID from object name.

There are many actions that accept MOID parameters.
```
- get_vmconsole_urls
- get_vms
- set_vm
- vm_check_tools
- vm_create_from_template
- vm_hw_cpu_mem_edit
- vm_hw_detail_get
- vm_hw_hdd_add
- vm_hw_nic_add
- vm_hw_nic_edit
- vm_hw_power_off
- vm_hw_power_on
- vm_hw_remove
- vm_hw_scsi_controller_add
- vm_hw_uuid_get
- wait_task
```
It's hard to correct interfaces of all these actions.

BTW, the `vm_hw_moid_get` action returns MOID of VirtualMachine from object-name of its, like this.
```
vagrant@ubuntu:~$ st2 run vsphere.vm_hw_moid_get vsphere=dc2 vm_names=www-group5-tmpl01
..
id: 58880f9d88fa3f1d14354c96
status: succeeded
parameters: 
  vm_names:
  - www-group5-tmpl01
  vsphere: dc2
result: 
  exit_code: 0
  result:
    www-group5-tmpl01: vm-292
  stderr: ''
  stdout: ''
vagrant@ubuntu:~$ 
```

But this action confines this transforming to the VirtualMachine.

I think the action that is generalized `vm_hw_moid_get` resolves this problem. 
This action (named `get_moid_from_name` FTTB) has two parameters,
 - object-name to convert to MOID.
 - vimType of object.

And this returns MOID according to the parameters.

If we had this `get_moid_from_name` action, the initial requirement would be satisfied without changing all above actions.
