### ISSUE TITLE
The ../actions/workflows/guest_process_run.yaml file is referenced but is not included in the repo

### ISSUE THREAD

**Issue by dustinupdyke** [StackStorm-Exchange/stackstorm-vsphere#42]
there is a file `../actions/guest_process_run.yaml` but no equivalent in `../actions/workflows`.

This results in errors from running vsphere commands such as `vsphere.guest_process_run`:

```json
{
  "traceback": "  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/container/base.py\", line 127, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/orquesta_runner/orquesta_runner.py\", line 85, in run\n    wf_def = self.get_workflow_definition(self.entry_point)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/orquesta_runner/orquesta_runner.py\", line 50, in get_workflow_definition\n    with open(entry_point, 'r') as def_file:\n",
  "error": "[Errno 2] No such file or directory: u'/opt/stackstorm/packs/vsphere/actions/workflows/guest_process_run.yaml'"
}
```

**Comment by LindsayHill** [comment]
@jeking3 looks like somehow we didn't include this file in #34 - you happen to have a copy of it?

**Comment by jeking3** [comment]
It's in the original PR:

https://github.com/StackStorm-Exchange/stackstorm-vsphere/pull/34/files#diff-306f944a0c3079d980209a2e682ca3c6

**Comment by LindsayHill** [comment]
@jeking3 as far as I can see, that PR only contains `actions/get_process_run.yaml` - it does not contain `actions/workflows/get_process_run.yaml`

**Comment by jeking3** [comment]
I submitted a PR however I haven't tested the yaml file... perhaps if someone else who wants to use the functionality could do that, we can fix the issue.

**Comment by LindsayHill** [comment]
Thanks @jeking3 

@dustinupdyke can you grab the workflow file from #43 and test it out?

**Comment by dustinupdyke** [comment]
Copied it into docker container via `$ docker cp guest_process_run.yaml st2-docker_stackstorm_1:opt/stackstorm/packs/vsphere/actions/workflows/guest_process_run.yaml` and get:
```
{
  "output": null,
  "errors": [
    {
      "language": "yaql",
      "type": "context",
      "spec_path": "tasks.file_upload.input",
      "schema_path": "properties.tasks.patternProperties.^\\w+$.properties.input",
      "message": "Variable \"script\" is referenced before assignment.",
      "expression": "<% ctx().script %>"
    },
    {
      "language": "yaql",
      "type": "context",
      "spec_path": "tasks.process_start.input",
      "schema_path": "properties.tasks.patternProperties.^\\w+$.properties.input",
      "message": "Variable \"arguments\" is referenced before assignment.",
      "expression": "<% ctx().arguments %> 1> stdout 2> stderr"
    }
  ]
}
```

**Comment by dustinupdyke** [comment]
Here is one I am working on locally that seems to perhaps getting further along, yet still manages to fail:

```
{
  "output": {
    "exit_code": -1,
    "stderr": "",
    "stdout": ""
  },
  "errors": [
    {
      "message": "Execution failed. See result for details.",
      "type": "error",
      "result": {
        "stdout": "",
        "result": "None",
        "stderr": "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py\", line 325, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py\", line 184, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/vsphere/actions/guest_dir_create.py\", line 43, in run\n    self.vm, self.guest_credentials, prefix, suffix)\n  File \"/opt/stackstorm/virtualenvs/vsphere/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 553, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/opt/stackstorm/virtualenvs/vsphere/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 362, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/opt/stackstorm/virtualenvs/vsphere/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 1240, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\npyVmomi.VmomiSupport.SystemError: (vmodl.fault.SystemError) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'A general system error occurred: vix error codes = (3016, 0).\\n',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   reason = 'vix error codes = (3016, 0).\\n'\n}\n",
        "exit_code": 1
      },
      "task_id": "dir_create"
    }
  ]
}
```

File:

```
version: '1.0'

description: Run a process inside a guest.

input:
  - vm_id
  - username
  - password
  - command
  - argument
  - vsphere

vars:
  - script_exit_code: -1
  - script_in_guest: ''
  - script_stdout: ''
  - script_stderr: ''
  - tempdir: ''

output:
  - exit_code: <% ctx().script_exit_code %>
  - stderr: <% ctx().script_stderr %>
  - stdout: <% ctx().script_stdout %>

tasks:
  dir_create:
    action: vsphere.guest_dir_create
    input:
      vm_id: <% ctx().vm_id %>
      username: <% ctx().username %>
      password: <% ctx().password %>
      prefix: "stackstorm_"
      suffix: "_scriptrunner"
      vsphere: <% ctx().vsphere %>
    next:
      - when: <% succeeded() %>
        publish: tempdir=<% result().result %>
        do: file_upload

  file_upload:
    action: vsphere.guest_file_upload
    input:
      vm_id: <% ctx().vm_id %>
      username: <% ctx().username %>
      password: <% ctx().password %>
      guest_directory: <% ctx().tempdir %>
      local_path: <% ctx().script %>
      vsphere: <% ctx().vsphere %>
    next:
      - when: <% succeeded() %>
        publish:
          - script_in_guest: <% result().result %>
        do: process_start
      - when: <% failed() %>
        do: dir_delete

  process_start:
    action: vsphere.guest_process_start
    input:
      vm_id: <% ctx().vm_id %>
      username: <% ctx().username %>
      password: <% ctx().password %>
      command: <% ctx().command %>
      arguments: <% ctx().arguments %> 1> stdout 2> stderr
      workdir: <% ctx().tempdir %>
      vsphere: <% ctx().vsphere %>
    next:
      - when: <% succeeded() %>
        publish: pid=<% result().result %>
        do: process_wait
      - when: <% failed() %>
        do: dir_delete

  process_wait:
    action: vsphere.guest_process_wait
    input:
      vm_id: <% ctx().vm_id %>
      username: <% ctx().username %>
      password: <% ctx().password %>
      pid: <% ctx().pid %>
    next:
      - publish: script_exit_code=<% result().exit_code %>
        do: get_stdout

  get_stdout:
    action: vsphere.guest_file_read
    input:
      vm_id: <% ctx().vm_id %>
      username: <% ctx().username %>
      password: <% ctx().password %>
      guest_directory: <% ctx().tempdir %>
      guest_file: <% stdout %>
    next:
      - publish: script_stdout=<% result().result %>
        do: get_stderr

  get_stderr:
    action: vsphere.guest_file_read
    input:
      vm_id: <% ctx().vm_id %>
      username: <% ctx().username %>
      password: <% ctx().password %>
      guest_directory: <% ctx().tempdir %>
      guest_file: <% stderr %>
    next:
      - publish: script_stderr=<% result().result %>
        do: dir_delete

  dir_delete:
    action: vsphere.guest_dir_delete
    input:
      vm_id: <% ctx().vm_id %>
      username: <% ctx().username %>
      password: <% ctx().password %>
      guest_directory: <% ctx().tempdir %>
      recursive: true
      vsphere: <% ctx().vsphere %>
    next:
      - when: <% ctx().script_exit_code != 0 %>
        do: fail
      
```
